apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: nginx-page
        mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-page
      configMap:
        name: nginx-config
  restartPolicy: Never

