apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-depl
  name: nginx-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-depl
  type: ClusterIP
